<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Сайт M50");?><?/*$APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "main_advantages_list",
    Array(
        "ACTIVE_DATE_FORMAT" => "",
        "ADD_SECTIONS_CHAIN" => "N",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "N",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "CHECK_DATES" => "Y",
        "DETAIL_URL" => "",
        "DISPLAY_BOTTOM_PAGER" => "N",
        "DISPLAY_DATE" => "N",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "N",
        "DISPLAY_PREVIEW_TEXT" => "N",
        "DISPLAY_TOP_PAGER" => "N",
        "FIELD_CODE" => array(
            0=>"ID",
            1=>"NAME",
            2=>"",
        f),
        "FILTER_NAME" => "",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "IBLOCK_ID" => "16",
        "IBLOCK_TYPE" => "prv_autoservice_about",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "INCLUDE_SUBSECTIONS" => "N",
        "MESSAGE_404" => "",
        "NEWS_COUNT" => "6",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "",
        "PAGER_TITLE" => "",
        "PARENT_SECTION" => "",
        "PARENT_SECTION_CODE" => "",
        "PREVIEW_TRUNCATE_LEN" => "",
        "PROPERTY_CODE" => array(
            0=>"ICON",
            1=>"",
        ),
        "SET_BROWSER_TITLE" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "N",
        "SET_META_KEYWORDS" => "N",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "N",
        "SHOW_404" => "N",
        "SORT_BY1" => "SORT",
        "SORT_BY2" => "ID",
        "SORT_ORDER1" => "ASC",
        "SORT_ORDER2" => "ASC",
        "STRICT_SECTION_CHECK" => "N",
    )
);*/?> <?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section.list",
	"main_services_list",
	Array(
		"ADD_SECTIONS_CHAIN" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_NOTES" => "",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPONENT_TEMPLATE" => "main_services_list",
		"COUNT_ELEMENTS" => "N",
		"COUNT_SECTIONS" => "6",
		"HIDE_SECTION_NAME" => "N",
		"IBLOCK_ID" => "18",
		"IBLOCK_TYPE" => "prv_autoservice_services",
		"SECTION_CODE" => "",
		"SECTION_FIELDS" => array(0=>"CODE",1=>"NAME",3=>"PICTURE",4=>"",),
		"SECTION_ID" => "",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(0=>"UF_PRICE",1=>"",),
		"SHOW_PARENT_NAME" => "N",
		"TOP_DEPTH" => "1",
		"VIEW_MODE" => "TILE"
	)
);?> <?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"main_about_list",
	Array(
		"ACTIVE_DATE_FORMAT" => "",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(0=>"ID",1=>"NAME",2=>"PREVIEW_TEXT",f),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "12",
		"IBLOCK_TYPE" => "prv_autoservice_about",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "6",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "",
		"PAGER_TITLE" => "",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(0=>"PREVIEW_IMG",1=>"",),
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "ID",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N"
	)
);?> <?/*$APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "main_about_team",
    Array(
        "ACTIVE_DATE_FORMAT" => "",
        "ADD_SECTIONS_CHAIN" => "N",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "N",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "CHECK_DATES" => "Y",
        "DETAIL_URL" => "",
        "DISPLAY_BOTTOM_PAGER" => "N",
        "DISPLAY_DATE" => "N",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "N",
        "DISPLAY_PREVIEW_TEXT" => "N",
        "DISPLAY_TOP_PAGER" => "N",
        "FIELD_CODE" => array(
            0=>"ID",
            1=>"NAME",
            2=>"PREVIEW_PICTURE",
        f),
        "FILTER_NAME" => "",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "IBLOCK_ID" => "14",
        "IBLOCK_TYPE" => "prv_autoservice_about",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "INCLUDE_SUBSECTIONS" => "N",
        "MESSAGE_404" => "",
        "NEWS_COUNT" => "10",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "",
        "PAGER_TITLE" => "",
        "PARENT_SECTION" => "",
        "PARENT_SECTION_CODE" => "",
        "PREVIEW_TRUNCATE_LEN" => "",
        "PROPERTY_CODE" => array(
            0=>"POST",
            1=>"",
        ),
        "SET_BROWSER_TITLE" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "N",
        "SET_META_KEYWORDS" => "N",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "N",
        "SHOW_404" => "N",
        "SORT_BY1" => "SORT",
        "SORT_BY2" => "ID",
        "SORT_ORDER1" => "ASC",
        "SORT_ORDER2" => "ASC",
        "STRICT_SECTION_CHECK" => "N"
    )
);*/?> <?/*$APPLICATION->IncludeComponent(
    "prvolga.autoservice:universal.feedback", 
    "feedback_main_banner", 
    array(
        "EMAIL_TO" => "",
        "EVENT_MESSAGE_ID" => array(
            0 => "12",
        ),
        "IBLOCK_ID" => "22",
        "IBLOCK_TYPE" => "prv_autoservice_feedback",
        "LINK_TO_PERSONAL" => SITE_DIR . "agreement",
        "PROPERTIES_CODE" => array(
            0 => "NAME",
            1 => "PHONE",
        ),
        "USE_PERSONAL" => "Y",
        "COMPONENT_TEMPLATE" => "feedback_main_banner"
    ),
    false
);*/?> <?/*$APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "main_news",
    Array(
        "ACTIVE_DATE_FORMAT" => "d.m.y",
        "ADD_SECTIONS_CHAIN" => "N",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "N",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "CHECK_DATES" => "Y",
        "COMPONENT_TEMPLATE" => "main_news",
        "DETAIL_URL" => "",
        "DISPLAY_BOTTOM_PAGER" => "N",
        "DISPLAY_DATE" => "Y",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "Y",
        "DISPLAY_PREVIEW_TEXT" => "N",
        "DISPLAY_TOP_PAGER" => "N",
        "FIELD_CODE" => array(0=>"ID",1=>"PREVIEW_TEXT",2=>"NAME",3=>"DATE_ACTIVE_FROM",4=>"PREVIEW_PICTURE"),
        "FILTER_NAME" => "",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "IBLOCK_ID" => "9",
        "IBLOCK_TYPE" => "prv_autoservice_articles",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "INCLUDE_SUBSECTIONS" => "N",
        "MESSAGE_404" => "",
        "NEWS_COUNT" => "3",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "",
        "PAGER_TITLE" => "",
        "PARENT_SECTION" => "",
        "PARENT_SECTION_CODE" => "",
        "PREVIEW_TRUNCATE_LEN" => "",
        "PROPERTY_CODE" => array(0=>"",1=>"",),
        "SET_BROWSER_TITLE" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "N",
        "SET_META_KEYWORDS" => "N",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "N",
        "SHOW_404" => "N",
        "SORT_BY1" => "SORT",
        "SORT_BY2" => "ID",
        "SORT_ORDER1" => "ASC",
        "SORT_ORDER2" => "ASC",
        "STRICT_SECTION_CHECK" => "N"
    )
);*/?> <?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section.list",
	"brand-slider-main",
	Array(
		"ADD_SECTIONS_CHAIN" => "N",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPONENT_TEMPLATE" => "brand-slider-main",
		"COUNT_ELEMENTS" => "Y",
		"FILTER_NAME" => "sectionsFilter",
		"IBLOCK_ID" => "10",
		"IBLOCK_TYPE" => "prv_autoservice_articles",
		"SECTION_CODE" => "",
		"SECTION_FIELDS" => array(0=>"",1=>"",),
		"SECTION_ID" => "",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(0=>"UF_CAR_IMG",1=>"",),
		"SHOW_PARENT_NAME" => "Y",
		"TOP_DEPTH" => "2",
		"VIEW_MODE" => "LINE"
	)
);?> <?/*$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"main_brand",
	Array(
		"ACTIVE_DATE_FORMAT" => "",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "main_brand",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(0=>"ID",1=>"PREVIEW_PICTURE",2=>"NAME",3=>"",),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "10",
		"IBLOCK_TYPE" => "prv_autoservice_articles",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "",
		"PAGER_TITLE" => "",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(0=>"",1=>"",),
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "ID",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N"
	)
);*/?>&nbsp;<?/*$APPLICATION->IncludeComponent(
	"prvolga.autoservice:instafeed", 
	"main_life", 
	array(
		"CACHE" => "21600",
		"CAPTION" => "Y",
		"CARUSEL_INLINE" => "4",
		"CARUSEL_RESIZE" => "square",
		"CARUSEL_SIDE_OFFSET" => "30",
		"CARUSEL_TOOLBAR" => "N",
		"CARUSEL_WIDGET_HEIGHT" => "auto",
		"CARUSEL_WIDGET_WIDTH" => "auto",
		"CLASSIC_BOTTOM_OFFSET" => "2",
		"CLASSIC_INLINE" => "3",
		"CLASSIC_OVERFLOW" => "hidden",
		"CLASSIC_RESIZE" => "square",
		"CLASSIC_SIDE_OFFSET" => "2",
		"CLASSIC_TOOLBAR" => "Y",
		"CLASSIC_WIDGET_HEIGHT" => "350px",
		"CLASSIC_WIDGET_WIDTH" => "350px",
		"COMPONENT_TEMPLATE" => "main_life",
		"COUNT" => "10",
		"HEAD" => "N",
		"LENGHT" => "100",
		"LOGIN" => "bmw_service_m50",
		"SEARCH" => "login",
		"WIDGET_TYPE" => "carusel"
	),
	false
);*/?><?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"main_portfolio",
	array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "8",
		"IBLOCK_TYPE" => "prv_autoservice_articles",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "TIMESTAMP_X",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"COMPONENT_TEMPLATE" => "main_news"
	),
	false
);?> <section id="contacts">
<div class="map_container">
	 <?$APPLICATION->IncludeComponent(
	"bitrix:map.yandex.view",
	"footer_map",
	Array(
		"API_KEY" => "",
		"COMPONENT_TEMPLATE" => "footer_map",
		"CONTROLS" => array(0=>"ZOOM",1=>"TYPECONTROL",2=>"SCALELINE",),
		"INIT_MAP_TYPE" => "MAP",
		"MAP_DATA" => "a:5:{s:10:\"yandex_lat\";d:59.92299499995499;s:10:\"yandex_lon\";d:30.377977999999988;s:12:\"yandex_scale\";i:16;s:10:\"PLACEMARKS\";a:1:{i:0;a:3:{s:3:\"LON\";d:30.377987890494;s:3:\"LAT\";d:59.922979430694;s:4:\"TEXT\";s:0:\"\";}}s:9:\"POLYLINES\";a:2:{i:0;a:3:{s:6:\"POINTS\";a:6:{i:0;a:2:{s:3:\"LAT\";d:59.922963479516;s:3:\"LON\";d:30.377713200803;}i:1;a:2:{s:3:\"LAT\";d:59.923127752338;s:3:\"LON\";d:30.37761127686;}i:2;a:2:{s:3:\"LAT\";d:59.923776983671;s:3:\"LON\";d:30.375877935065;}i:3;a:2:{s:3:\"LAT\";d:59.924909336411;s:3:\"LON\";d:30.377642828597;}i:4;a:2:{s:3:\"LAT\";d:59.923229746431;s:3:\"LON\";d:30.382116875993;}i:5;a:2:{s:3:\"LAT\";d:59.923850306236;s:3:\"LON\";d:30.385908514704;}}s:5:\"TITLE\";s:4:\"АН\";s:5:\"STYLE\";a:2:{s:11:\"strokeColor\";s:8:\"FF00007F\";s:11:\"strokeWidth\";i:3;}}i:1;a:3:{s:6:\"POINTS\";a:12:{i:0;a:2:{s:3:\"LAT\";d:59.915020779989476;s:3:\"LON\";d:30.3493106943593;}i:1;a:2:{s:3:\"LAT\";d:59.913947052031965;s:3:\"LON\";d:30.35684846142243;}i:2;a:2:{s:3:\"LAT\";d:59.91356992656796;s:3:\"LON\";d:30.36234162548492;}i:3;a:2:{s:3:\"LAT\";d:59.91387162728309;s:3:\"LON\";d:30.369916183742976;}i:4;a:2:{s:3:\"LAT\";d:59.914391800128485;s:3:\"LON\";d:30.37474502387602;}i:5;a:2:{s:3:\"LAT\";d:59.91696600078;s:3:\"LON\";d:30.37470239041709;}i:6;a:2:{s:3:\"LAT\";d:59.92425369884328;s:3:\"LON\";d:30.372054071171142;}i:7;a:2:{s:3:\"LAT\";d:59.924486461503705;s:3:\"LON\";d:30.372126452861476;}i:8;a:2:{s:3:\"LAT\";d:59.92492001230163;s:3:\"LON\";d:30.372705810008682;}i:9;a:2:{s:3:\"LAT\";d:59.9249115953902;s:3:\"LON\";d:30.372759436079477;}i:10;a:2:{s:3:\"LAT\";d:59.92312206099601;s:3:\"LON\";d:30.377576880119427;}i:11;a:2:{s:3:\"LAT\";d:59.922965867157416;s:3:\"LON\";d:30.37768953289806;}}s:5:\"TITLE\";s:0:\"\";s:5:\"STYLE\";a:2:{s:11:\"strokeColor\";s:8:\"0054A57F\";s:11:\"strokeWidth\";i:3;}}}}",
		"MAP_HEIGHT" => "470",
		"MAP_ID" => "map",
		"MAP_WIDTH" => "100%",
		"OPTIONS" => array(0=>"ENABLE_DBLCLICK_ZOOM",1=>"ENABLE_RIGHT_MAGNIFIER",2=>"ENABLE_DRAGGING",)
	)
);?>
</div>
<div class="container">
	<div class="map_content">
		<h3><?=GetMessage('PRV_FOOTER_CONTACTS_HEADER')?></h3>
		<div class="map_content_text">
			<p>
 <i class="fa fa-map-marker"></i>г. Санкт-Петербург, ул. Миргородская, 30
			</p>
			<p>
 <i class="fa fa-phone"></i><a href="tel:+78126112311">+7 (812) 611-23-11</a>
			</p>
			<p>
 <i class="fa fa-envelope-o"></i><a href="mailto:m50bmw@mail.ru">m50bmw@mail.ru</a>
			</p>
			<p>
 <i class="fa fa-clock-o"></i>Ежедневно с 10:00 до 20:00
			</p>
		</div>
		<div class="btn_cnt">
			<div class="sn_cnt">
 <a href="https://www.instagram.com/bmw_service_m50" title="<?=GetMessage('PRV_FOOTER_YOUR_LINK');?>" class="social_network sn_insta" target="_blank" rel="nofollow"><i class="fa fa-instagram"></i></a>
			</div>
 <a href="#" class="btn callme_btn" data-toggle="modal" data-target="#callbackModal"><?=GetMessage('PRV_FOOTER_BUTTON_CALLBACK')?></a>
			<div class="clearfix">
			</div>
		</div>
	</div>
</div>
 <!-- .container --> </section> <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>